name: nugasyuk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo nugasyuk.png
    - images/animasi mahasiswa.png
    - images/google.png
    - images/Account icon.png
    - images/Forgot password illustration.png
    - images/back button.png
    - images/Profile Picture.png
    - images/notelist.png 
    - images/presentation.png
    - images/avatar.png
    - images/todo.svg
    - images/progress.svg
    - images/done.svg
    - images/late.svg